name: debug_overlay
description: View debug infos and change settings via a central overlay for your app.
version: 0.2.11
repository: https://github.com/JonasWanke/debug_overlay
screenshots:
  - description: DeviceInfoDebugHelper
    path: doc/helpers-deviceInfo.png
  - description: MediaQueryDebugHelper
    path: doc/helpers-mediaQuery.png
  - description: LogsDebugHelper
    path: doc/helpers-logs.png
  - description: MediaOverridesDebugHelper
    path: doc/helpers-mediaOverrides.png
  - description: PackageInfoDebugHelper
    path: doc/helpers-packageInfo.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  black_hole_flutter: ^1.1.0
  collection: ^1.19.1
  data_size: ^0.2.0
  device_info_plus: ^12.2.0
  flutter:
    sdk: flutter
  implicitly_animated_list: ^2.1.1
  json_view: ^0.4.2
  meta: ^1.15.0
  package_info_plus: ^9.0.0
